import sys
import telnetlib
#enter
user = 'login'
password = 'password'
A=['172.17.71.24','172.17.71.25','172.17.8.19']
for host in A:
        a=host[7:16]
	tn = telnetlib.Telnet(host)
	tn.read_until('UserName:')
	tn.write(user)
	tn.write('\n')
	tn.read_until('PassWord:')
	tn.write(password)
	tn.write('\n')
	tn.read_until('UserName:')
	tn.write(user)
	tn.write('\n')
	tn.read_until('PassWord:')
	tn.write(password)
	tn.write('\n')
	tn.read_until('DES-3028')
#IGMP
        tn.write('config multicast port_filtering_mode all  filter_unregistered_groups')
        tn.write('\n')
        tn.write('create mcast_filter_profile profile_id 1 profile_name tv')
        tn.write('\n')
        tn.write('config mcast_filter_profile profile_id 1 add 224.0.0.1 - 224.0.0.2')
        tn.write('\n')
        tn.write('config limited_multicast_addr ports 1-24 add profile_id 1')
        tn.write('\n')
        tn.write('create mcast_filter_profile profile_id 2 profile_name tv1')
        tn.write('\n')
        tn.write('config mcast_filter_profile profile_id 2 add 224.10.10.1 - 224.10.10.250')
        tn.write('\n')
        tn.write('config limited_multicast_addr ports 1-24 add profile_id 2')
        tn.write('\n')
        tn.write('enable igmp_snooping')
        tn.write('\n')
	tn.read_until('DES-3028')
        tn.write('enable igmp_snooping multicast_vlan')
        tn.write('\n')
	tn.read_until('DES-3028')
        tn.write('create igmp_snooping multicast_vlan Net_IPTV 450')
        tn.write('\n')
	tn.read_until('DES-3028')
        tn.write('config igmp_snooping multicast_vlan Net_IPTV state enable')
        tn.write('\n')
	tn.read_until('DES-3028')
        tn.write('config igmp_snooping multicast_vlan Net_IPTV replace_source_ip 172.30.'+a)
        tn.write('\n')
        tn.write('config igmp_snooping multicast_vlan Net_IPTV add member_port 1-24')
        tn.write('\n')
        tn.write('config igmp_snooping multicast_vlan Net_IPTV add source_port 25-28')
        tn.write('\n')
	tn.read_until('DES-3028')
        tn.write('config igmp_snooping vlan_name Net_IPTV fast_leave enable')
        tn.write('\n')
	tn.read_until('DES-3028')
        tn.write('config router_ports Net_IPTV add 25-26')
        tn.write('\n')
#QoS
        tn.write('config 802.1p user_priority 0 1')
        tn.write('\n')
        tn.write('config 802.1p user_priority 1 0')
        tn.write('\n')
        tn.write('config 802.1p user_priority 2 0')
        tn.write('\n')
        tn.write('config 802.1p user_priority 3 1')
        tn.write('\n')
        tn.write('config 802.1p user_priority 4 2')
        tn.write('\n')
        tn.write('config 802.1p user_priority 5 2')
        tn.write('\n')
        tn.write('config 802.1p user_priority 6 3')
        tn.write('\n')
        tn.write('config 802.1p user_priority 7 3')
        tn.write('\n')
        tn.write('config 802.1p default_priority 1-28 0')
        tn.write('\n')
        tn.write('config bandwidth_control 1-28 rx_rate no_limit tx_rate no_limit')
        tn.write('\n')
#ACL
        tn.write('create access_profile ip destination_ip_mask 255.255.255.0 profile_id 123')
        tn.write('\n')
        tn.write('config access_profile profile_id 123 add access_id 1 ip destination_ip 224.10.10.0 port 25 permit priority 5')
        tn.write('\n')
        tn.write('config access_profile profile_id 123 add access_id 2 ip destination_ip 224.10.10.0 port 26 permit priority 5')
        tn.write('\n')

#Filter_NetBios
	tn.write('create access_profile ip tcp dst_port_mask 0xFFFF profile_id 30')
        tn.write('\n')
	tn.write('config access_profile profile_id 30 add access_id auto_assign ip tcp dst_port 135 port 1-28 deny')
        tn.write('\n')
	tn.write('config access_profile profile_id 30 add access_id auto_assign ip tcp dst_port 137 port 1-28 deny')
        tn.write('\n')
	tn.write('config access_profile profile_id 30 add access_id auto_assign ip tcp dst_port 138 port 1-28 deny')
        tn.write('\n')
	tn.write('config access_profile profile_id 30 add access_id auto_assign ip tcp dst_port 139 port 1-28 deny')
        tn.write('\n')
	tn.write('config access_profile profile_id 30 add access_id auto_assign ip tcp dst_port 445 port 1-28 deny')
        tn.write('\n')
	tn.write('create access_profile ip udp dst_port_mask 0xFFFF profile_id 40')
        tn.write('\n')
	tn.write('config access_profile profile_id 40 add access_id auto_assign ip udp dst_port 135 port 1-28 deny')
        tn.write('\n')
	tn.write('config access_profile profile_id 40 add access_id auto_assign ip udp dst_port 137 port 1-28 deny')
        tn.write('\n')
	tn.write('config access_profile profile_id 40 add access_id auto_assign ip udp dst_port 138 port 1-28 deny')
        tn.write('\n')
	tn.write('config access_profile profile_id 40 add access_id auto_assign ip udp dst_port 139 port 1-28 deny')
        tn.write('\n')
	tn.write('config access_profile profile_id 40 add access_id auto_assign ip udp dst_port 445 port 1-28 deny')
        tn.write('\n')

#SAVE
        tn.write('save config')
        tn.write('\n')
        tn.read_until('Success')
        tn.write('\n')
        tn.write('logout')
        tn.write('\n')
        print host

